name: DevSecOps Pipeline

on:
  push:
    branches: [main]

jobs:
  semgrep:
    name: ðŸ›¡ï¸ Semgrep Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep/rules.yml

  test:
    name: ðŸ§ª Pytest Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest tests/

  dependency-check:
    name: ðŸ” OWASP Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "smtp-validator"
          path: "."
          format: "HTML"
          out: "reports"
      - name: Upload OWASP report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/

  
  docker:
    name: ðŸ³ Docker Build, Scan & Push
    runs-on: ubuntu-latest
    needs: [semgrep, test, dependency-check, sonarqube]
    steps:
      - uses: actions/checkout@v3

      - name: Set version tag
        id: vars
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t yourdockerhubuser/smtp-validator:${{ env.VERSION }} .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: yourdockerhubuser/smtp-validator:${{ env.VERSION }}
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag yourdockerhubuser/smtp-validator:${{ env.VERSION }} yourdockerhubuser/smtp-validator:latest
          docker push yourdockerhubuser/smtp-validator:${{ env.VERSION }}
          docker push yourdockerhubuser/smtp-validator:latest
